site_name: Ktvn
theme:
  name: material
nav:
  - Welcome: 'index.md'
  - Getting Started: 'getting-started.md'
  - DSL: 'dsl.md'
  - Game Engine: 'game-engine.md'
  - Api documentation: 'api-documentation.md'
