/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.9.10"

    // https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow
    id("com.github.johnrengelman.shadow") version "8.1.1"

    // https://plugins.grajlleitschuh.gradle.ktlintdle.org/plugin/org.
    id("org.jlleitschuh.gradle.ktlint") version "11.5.1"

    // https://plugins.gradle.org/plugin/org.sonarqube
    id("org.sonarqube") version "4.3.1.3277"

    // https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt
    id("io.gitlab.arturbosch.detekt") version "1.23.1"

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Appy the Java library plugin
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Use Log4J for logging purposes.
    // https://logging.apache.org/log4j/kotlin/index.html
    // https://github.com/apache/logging-log4j-kotlin
    implementation("org.apache.logging.log4j:log4j-api-kotlin:1.2.0")
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")

    // https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-gradle-plugin
    implementation("io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.23.1")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Use the ktaf library
    implementation(project(":ktvn"))
    implementation(project(":ktvn-examples"))

    // Use the ktaf example
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.benpollarduk.ktvn.prototyping.swing.App")
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "com.github.benpollarduk.ktvn.prototyping.swing.App"
        )
    }
}

tasks.compileKotlin {
    // Treat all warnings as errors
    kotlinOptions.allWarningsAsErrors = true
}
