name: main-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Execute Gradle build, test and Jacoco test report generation
      run: |
        sh ./gradlew build test jacocotestreport
    - name: Publish JaCoCo test report
      run: |
        mkdir -p ${{ github.workspace }}/build/reports/jacoco/test
        cp -r ktvn/build/reports/jacoco/test jacoco-report
      if: always()
    - name: Upload JaCoCo test report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: jacoco-report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
