name: publish-docs

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Restrict to owner
        if: github.actor != 'benpollarduk'
        run: |
          echo "Access denied for user ${{ github.actor }}"
          exit 1
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: benpollarduk/ktvn
          token: ${{ secrets.PAT }}
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install pip
        run: |
          sudo apt update
          sudo apt install python3-pip

      - name: Install mkdocs
        run: |
          pip install mkdocs-material

      - name: Build mkdocs documentation
        run: |
          cd docs/mkdocs/
          mkdocs build

      - name: Copy website files, commit, then push changes to ktvn-docs
        run: |
          mkdir ktvn-docs
          cd ktvn-docs
          git init
          git remote add origin https://${{ secrets.PAT }}@github.com/benpollarduk/ktvn-docs.git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch
          git checkout main
          git rm -r --ignore-unmatch .
          cp -r ../docs/mkdocs/site/* .
          git add .
          git commit -m "Update documentation"
          git push https://${{ secrets.PAT }}@github.com/benpollarduk/ktvn-docs.git HEAD:main
          
